# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Lan Phan
    url: /aboutme/
    weight: 20
  - name: Research
    url: /research/
    weight: 30
  - name: Publications
    url: /publication/
    weight: 40
  - name: News
    url: /news/
    weight: 50
  - name: Gallery
    url: /gallery/
    weight: 60

