# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 20
  - name: Team
    url: /people/
    weight: 30
  - name: Publications
    url: /publication/
    weight: 40
  - name: News
    url: /post/
    weight: 50

